/*
 *  CART MUTATIONS
 */
export const INIT_BEER_LIST = "INIT_BEER_LIST";

/*
 *  CART MUTATIONS
 */
export const PUSH_BEER_TO_CART_LIST = "PUSH_BEER_TO_CART_LIST";
export const DELETE_BEER_FROM_CART_LIST = "DELETE_BEER_FROM_CART_LIST";
