/*
 *  INIT BEER LIST
 */
export const INIT_BEER_LIST = "INIT_BEER_LIST";

/*
 *  BEER CART MUTATIONS
 */
export const PUSH_BEER_TO_CART_LIST = "PUSH_BEER_TO_CART_LIST";
export const DELETE_BEER_FROM_CART_LIST = "DELETE_BEER_FROM_CART_LIST";

/*
 *  SEARCH BEER
 */
export const SEARCH_BEER = "SEARCH_BEER";
